name: Features - Auto

on:
  repository_dispatch:
    types: [update-event]
 
 

jobs:
  download-and-extract:
    runs-on: ubuntu-latest
    env:
      MAIL_ID: ${{ secrets.MAIL_ID }}
      NAME: ${{ secrets.NAME }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      PIN_MSG: ${{ secrets.PIN_MSG }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
   

    - name: Install modules
      run: |
        pip install -r requirements.txt


    - name: Download & Extract
      run: |        
        python main.py ${{ github.event.client_payload.vername_type }}
        
        

    - name: Add extracted file to Git
      run: |
        vername=$(jq -r '.version_name' manifest.json)
        git config --global user.email "${{ env.MAIL_ID }}"
        git config --global user.name "${{ env.NAME }}"
        git pull
        git add .
        git commit -m "${vername}"
        git push


    - name: Commit data
      uses: rlespinasse/git-commit-data-action@v1
    
      
    - name: Changes to Telegram
      run: |
        vername=$(jq -r '.version_name' manifest.json)       
        python changes.py $vername ${{ github.event.client_payload.msg_id }} ${{ env.GIT_COMMIT_SHA }} ${{ env.BOT_TOKEN }} ${{ env.CHANNEL_ID }} ${{ env.PIN_MSG }}